### ISSUE TITLE
Request dataset

### ISSUE THREAD

**Issue by igip-liu** [limingwu8/UNet-pytorch#3]
Could you send me a copy of the dataset, please? I want to learn it. My email  is 734841570@qq.com

**Comment by limingwu8** [comment]
I think they are available for downloading in Kaggle.

**Comment by igip-liu** [comment]
Thank you for the response
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Liming Wu"<notifications@github.com>;
 发送时间: 2019年8月17日(星期六) 凌晨0:03
 收件人: "limingwu8/UNet-pytorch"<UNet-pytorch@noreply.github.com>;
 抄送: "734841570"<734841570@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [limingwu8/UNet-pytorch] Request dataset (#3)

 

 
Closed #3.

**Comment by igip-liu** [comment]
Thank you for the response

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Liming Wu"<notifications@github.com>;
 发送时间: 2019年8月17日(星期六) 凌晨0:03
 收件人: "limingwu8/UNet-pytorch"<UNet-pytorch@noreply.github.com>;
 抄送: "734841570"<734841570@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [limingwu8/UNet-pytorch] Request dataset (#3)

 

 
I think they are available for downloading in Kaggle.

**Comment by manvirvirk** [comment]
what is the dataset directory??
